### PR TITLE
Hostname first

### PR DESCRIPTION
**Pull request by HamzaJarane**

### CODE REVIEW

**Review by oylsister — CHANGES_REQUESTED** [review]
Prefer having option to switch a place for hostname status rather than completely unchangeable.

**Comment by HamzaJarane** [comment]
that is better? 942af62b62347815b0ba49b8ebac1076e120586c

**Review by oylsister — CHANGES_REQUESTED** [review]
Look so far good for me.
But why you deleted translation file in csgo folder?
bring them back.

**Review by oylsister — APPROVED** [review]

**Comment by oylsister** [comment]
Thanks for contribution

**Pull request merged**
